spring.application.name=petshop
# Nome da aplicação
spring.application.name=petshop

# Configuração do Banco de Dados H2 (Em memória)
spring.datasource.url=jdbc:h2:mem:petshopdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Habilitar o console web do H2 para visualizar a tabela no navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Atualizar a estrutura da tabela automaticamente
spring.jpa.hibernate.ddl-auto=update